# vim:ft=kitty

## name:     Ayu Darker
## source:   ayu_darker.json (Ayu Darker)

# The basic colors
foreground              #bfbdb6
background              #080808
selection_foreground    #080808
selection_background    #5ac2fe

# Cursor colors
cursor                  #5ac1fe
cursor_text_color       #080808

# URL underline color when hovering with mouse
url_color               #fe8f40

# Kitty window border colors
active_border_color     #1b4a6e
inactive_border_color   #3f4043
bell_border_color       #feb454

# OS Window titlebar colors
wayland_titlebar_color  #313337
macos_titlebar_color    #080808

# Tab bar colors
active_tab_foreground   #cbf2e4
active_tab_background   #1f2127
active_tab_font_style   bold
inactive_tab_foreground #8a8986
inactive_tab_background #0d1016
inactive_tab_font_style normal
tab_bar_background      #080808

# Colors for marks (marked text in the terminal)
mark1_foreground #080808
mark1_background #5ac1fe
mark2_foreground #080808
mark2_background #fe8f40
mark3_foreground #080808
mark3_background #aad84c

# The 16 terminal colors

# black
color0 #0d1016
color8 #545557

# red
color1 #ef7177
color9 #febab9

# green
color2  #aad84c
color10 #d8eca8

# yellow
color3  #feb454
color11 #ffd9aa

# blue
color4  #5ac1fe
color12 #b7dffe

# magenta
color5  #39bae5
color13 #addcf3

# cyan
color6  #95e5cb
color14 #cbf2e4

# white
color7  #bfbdb6
color15 #bfbdb6
